[package]
name = "ctap-common"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
log = "0.4"
rand = "0.8"

[target.'cfg(target_os = "linux")'.dependencies]
hidapi = { version = "2.6", default-features = false, features = ["linux-native"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
hidapi = "2.6"
